#!/bin/sh

echo_blue() {
  printf '\033[0;36m%s\033[0m\n' "$1"
}

echo_yellow() {
  printf '\033[0;33m%s\033[0m\n' "$1"
}

if ! command -v scalafmt; then
  echo "Please install scalafmt to execute the pre-commit script. Command not found: scalafmt"
  exit 1
fi

echo_blue "[Scalafmt] Checking formatting..."

if ! scalafmt --reportError; then
  echo_yellow "[Scalafmt] Some files are invalid or were reformatted, please review and commit again."
  exit 1
fi
